service: livle-server

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-2
  stage: dev
  profile: livle-serverless

functions:
  usersCreate:
    handler: handler.usersCreate
    events:
      - http:
          path: users
          method: post
          cors: true
